- name: pull juicebox image
  community.docker.docker_image:
    name:  bkimminich/juice-shop:latest
    source: pull

- name: start juicebox container
  community.docker.docker_container:
    name: juice-shop-app
    image: bkimminich/juice-shop:latest
    state: started
    restart: yes

