---
# tasks insttall Declaritive Onboarding Latest

#Bypass for userAuth
 - ansible.builtin.stat:
     path: ~/credentials.yml
   register: credentials_bypass

 - ansible.builtin.include_vars:
     path: ~/credentials.yml
   when: credentials_bypass.stat.exists