---
- name: USECASE2-AS3
  hosts: lb
  connection: local
  gather_facts: false

  vars_files:
    - vars/f5_vars.yml
  tasks:
#    - name: CREATE AS3 JSON BODY
#      set_fact:
#        as3_app_body: "{{ lookup('template', 'j2/as3_template.j2', split_lines=False) }}"

    - debug:
        msg: "https://bitbucket.org/vdi-tech-guy/{{repo_name}}/raw/master/{{ASM_Final_File_Name}}"


    - name: PUSH AS3
      uri:
        url: "https://{{ ansible_host }}:8443/mgmt/shared/appsvcs/declare"
        method: POST
        body: "{{ lookup('template','j2/configure_as3.j2', split_lines=False) }}"
        status_code: 200
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        validate_certs: false
      delegate_to: localhost
