---
- name: USECASE1-AS3
  hosts: lb
  connection: local
  gather_facts: false

  vars:
    pool_members: "{{ groups['web'] }}"
    F5_Admin_Port: "8443"
    F5_VIP_Name: Use-Case-1-VIP


  tasks:
#    - name: CREATE AS3 JSON BODY
#      set_fact:
#        as3_app_body: "{{ lookup('template', 'j2/as3_template.j2', split_lines=False) }}"


    - name: Check if Previous AS3 Command was run
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:8443/mgmt/tm/ltm/virtual"
        method: GET
        return_content: yes
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        validate_certs: false
      delegate_to: localhost
      register: previous_as3

    - name: Check if Previous UseCases exists
      ansible.builtin.set_fact:
        usecase: "{{ item }}"
      with_items: "{{ previous_as3.json['items'] }}"
      when: item.description != F5_VIP_Name

    - name: PUSH AS3
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:{{ F5_Admin_Port }}/mgmt/shared/appsvcs/declare"
        method: POST
        body: "{{ lookup('template','j2/https.j2', split_lines=False) }}"
        status_code: 200
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        validate_certs: false
      delegate_to: localhost
      when: usecase is not defined
      
