---
- name: USECASE4-AS3
  hosts: lb
  connection: local
  gather_facts: false

  vars_files:
    - vars/f5_vars.yml

  tasks:
    - name: CREATE AS3 JSON BODY
      set_fact:
        as3_app_body: "{{ lookup('template', 'j2/app_maint.j2', split_lines=False) }}"

    - debug:
        var: as3_app_body