- name: Ensure Community Grid is disabled
  ansible.builtin.systemd:
    name: boinc-client
    state: stopped
    enabled: false
  ignore_errors: yes

- name: Add Docker GPG key
  ansible.builtin.rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/centos/docker-ce.repo"
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: install yum-utils
  ansible.builtin.yum: 
    name: 
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - iptables
    - docker-ce
    - docker-ce-cli
    - python3
    state: present

# Install (Docker) python package.
- ansible.builtin.pip:
    name: docker

- name: start docker-ce
  ansible.builtin.service:
    name: docker
    state: started
